apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinema-edge-ingress
  namespace: cinema-ticketing
  annotations:
    # Use $1 to capture the full path and forward it intact to the gateway
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: cinema-booking.local
      http:
        paths:
          # Use a regex match to grab the entire path after the domain
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080