server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_db
    username: postgres
    password: local_dev_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true