apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: {{ .Values.global.namespace }}
data:
  USER_SERVICE_DB_URL: "jdbc:postgresql://postgres-user-service:5432/user_db"
  MOVIE_SERVICE_DB_URL: "jdbc:postgresql://postgres-movie-service:5432/movie_db"
  BOOKING_SERVICE_DB_URL: "jdbc:postgresql://postgres-booking-service:5432/booking_db"
  PAYMENT_SERVICE_DB_URL: "jdbc:postgresql://postgres-payment-service:5432/payment_db"